# Generated by Django 5.1.1 on 2024-10-11 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('technology_used', models.CharField(blank=True, max_length=255)),
                ('testimonial', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lable_to_show', models.CharField(choices=[('site', 'Site'), ('design', 'Design'), ('content', 'Content'), ('seo', 'SEO'), ('social', 'Social')], default='site', max_length=10, verbose_name='show in portfolio')),
                ('image1', models.ImageField(blank=True, upload_to='portfolio_images/')),
                ('image2', models.ImageField(blank=True, upload_to='portfolio_images/')),
                ('image3', models.ImageField(blank=True, upload_to='portfolio_images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.category')),
                ('tags', models.ManyToManyField(blank=True, to='portfolio.tag')),
            ],
        ),
    ]
